### ISSUE TITLE
Como que eu uso essa api?

### ISSUE THREAD

**Issue by victoromarques** [deividfortuna/molicar#1]
Gostaria de saber como que eu instancio a api pra fazer rodar!

**Comment by pgsbird** [comment]
Estou com essa dúvida também, tentei utilizar o npm start para iniciar, mas dá problema de "supervisor"

**Comment by victoromarques** [comment]
Até agora não consegui fazer funcionar! sempre da erro em alguma dependência!

**Comment by deividfortuna** [comment]
Eu arrumei o problema realacionado a executar o `npm start` mas parece que a molicar fez algum tipo de bloqueio ainda preciso investigar melhor. Malz ai :disappointed:

**Comment by pgsbird** [comment]
Tranquilo, mas obrigado por responder, vou tentar ajudar então fazendo alguma coisa...

**Comment by victoromarques** [comment]
Vlw, se precisar de ajuda me fala, funcionando me fala que eu tenho interesse em $$$! Muito obrigado!

**Comment by thiago-vsl** [comment]
Esse bloqueio da Molicar ainda continua ativo?

**Comment by JonatanPotrikus** [comment]
Acho que deve ter algo ligado a isso:

![image](https://user-images.githubusercontent.com/28599893/62739331-f0913c00-ba0a-11e9-8ff6-7b10d770d6c8.png)

Acho que nao é mais free como era.

**Comment by deividfortuna** [comment]
A Molicar tirou do ar o aplicativo mobile que eu usava para disponibilizar essa API.
Infelizmente ainda não consegui achar outra alternativa. Recomendo usar a FIPE: 
https://github.com/deividfortuna/fipe
Abraço
